version: 2.1

orbs:
  node: circleci/node@5

jobs:
  checkoutEtTests:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Clone du backend
          command: git clone https://github.com/SebDeli/Labo1BackEnd backend
      - run:
          name: Installation des dépendances backend
          command: |
            cd backend
            npm install
      - run:
          name: Exécution des tests
          command: |
            cd backend
            npm run test
      - store_test_results:
          path: backend/test-results/

  integrationFrontend:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Clone du backend
          command: git clone https://github.com/SebDeli/Labo1BackEnd backend
      - run:
          name: Clone du frontend
          command: git clone https://github.com/SebDeli/Labo1FrontEnd frontend
      - run:
          name: Installation des dépendances frontend
          command: |
            cd frontend
            npm install
      - run:
          name: Build du frontend
          command: |
            cd frontend
            npm run build
      - run:
          name: Préparation du backend pour le déploiement
          command: |
            cd backend
            mkdir -p public
            cp -r ../frontend/build/* public/
      - persist_to_workspace:
          root: backend
          paths:
            - public

  deploiement:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Vérification du contenu du backend
          command: ls -Rl /workspace

workflows:
  build-and-deploy:
    jobs:
      - checkoutEtTests
      - integrationFrontend:
          requires:
            - checkoutEtTests
      - deploiement:
          requires:
            - integrationFrontend
